name: Release

on:
  release:
    types: [published]

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install tfx-cli globally
        run: npm install -g tfx-cli

      - name: Package extension
        run: npm run package

      - name: Publish to Azure DevOps Marketplace
        run: npm run publish
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}
